Repository softeer5th/Team3-PowerPenguin, pull requests merged in 2025-02, with the labels that each got.

#20 [FE] ModalInput UI 구현
  front-end/src/components/input/ModalInput.module.css
  front-end/src/components/input/ModalInput.tsx
  front-end/src/main.tsx
Labels: ✨ Feat, ⚛️ FE

#21 [FE] CategoryChip UI 구현
  front-end/src/components/chip/CategoryChip.module.css
  front-end/src/components/chip/CategoryChip.tsx
Labels: ✨ Feat, ⚛️ FE

#22 [FE]Text Button 구현
  front-end/src/components/button/text/ClassCloseButton.tsx
  front-end/src/components/button/text/TextButton.module.css
  front-end/src/components/button/text/TextButton.tsx
Labels: ✨ Feat, ⚛️ FE

#26 [BE] Google OAuth를 통한 회원가입&로그인 기능 구현
  back-end/reacton/build.gradle
  back-end/reacton/src/main/java/com/softeer/reacton/domain/professor/Professor.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/professor/ProfessorRepository.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/config/WebClientConfig.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/jwt/JwtAuthenticationFilter.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/jwt/JwtTokenUtil.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/oauth/OAuthConfig.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/oauth/OAuthController.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/oauth/OAuthProvider.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/oauth/OAuthService.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/oauth/dto/GoogleUserProfile.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/oauth/dto/LoginResponse.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/oauth/dto/OAuthTokenResponse.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/oauth/dto/UserProfile.java
Labels: ✨ Feat, 🌱 BE

#24 [FE] Dropdown UI 구현
  front-end/src/assets/icons/down-vector.svg
  front-end/src/components/dropdown/DropDown.module.css
  front-end/src/components/dropdown/DropDown.tsx
  front-end/src/index.css
Labels: ✨ Feat, ⚛️ FE

#28 [FE] Global Modal 구현
  front-end/src/assets/icons/modal-check.svg
  front-end/src/assets/icons/question-mark.svg
  front-end/src/assets/icons/warning.svg
  front-end/src/components/modal/AlertModal.module.css
  front-end/src/components/modal/AlertModal.tsx
  front-end/src/components/modal/FileChangeFailPopup.tsx
  front-end/src/components/modal/FileLoadingPopup.tsx
  front-end/src/components/modal/FileOpenFailPopup.tsx
  front-end/src/components/modal/FileUploadPopupModal.module.css
  front-end/src/components/modal/FileUploadPopupModal.tsx
  front-end/src/components/modal/Modal.tsx
  front-end/src/components/modal/PopupModal.module.css
  front-end/src/components/modal/PopupModal.tsx
Labels: ✨ Feat, ⚛️ FE

#30 [FE] Text Button 스타일 오류 수정
  front-end/src/components/button/text/TextButton.tsx
Labels: 🐞 Fix, ⚛️ FE

#31 [BE] 회원가입 기능
  back-end/reacton/src/main/java/com/softeer/reacton/domain/professor/Professor.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/professor/ProfessorController.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/professor/ProfessorService.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/config/CookieConfig.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/jwt/JwtAuthenticationFilter.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/jwt/JwtTokenUtil.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/oauth/OAuthController.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/oauth/OAuthService.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/oauth/dto/GoogleUserProfile.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/oauth/dto/LoginResponse.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/oauth/dto/OAuthLoginResult.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/oauth/dto/UserProfile.java
Labels: ✨ Feat, 🌱 BE

#34 [BE] 회원가입 토큰 검증 실패 및 메서드명 에러
  back-end/reacton/src/main/java/com/softeer/reacton/domain/professor/ProfessorService.java
Labels: 🐞 Fix, 🌱 BE

#36 [BE] Netty 최신 버전 추가
  back-end/reacton/build.gradle
Labels: 🐞 Fix, 🔧 Chore, 🌱 BE

#42 [FE] 라우팅 설정
  front-end/src/App.tsx
  front-end/src/pages/professor/course/index.tsx
  front-end/src/pages/professor/home/index.tsx
  front-end/src/pages/professor/longin/index.tsx
  front-end/src/pages/professor/register/index.tsx
  front-end/src/pages/professor/search/index.tsx
  front-end/src/pages/student/course/index.tsx
  front-end/src/pages/student/home/index.tsx
Labels: ✨ Feat, ⚛️ FE

#38 [BE] 백엔드 예외 처리 기능 구현
  back-end/reacton/src/main/java/com/softeer/reacton/domain/professor/ProfessorService.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/exception/BaseException.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/exception/Controller/CustomErrorController.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/exception/ExceptionResponse.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/exception/Handler/GlobalExceptionHandler.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/exception/code/ErrorCode.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/exception/code/GlobalErrorCode.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/exception/code/JwtErrorCode.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/exception/code/OAuthErrorCode.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/exception/code/ProfessorErrorCode.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/jwt/JwtAuthenticationFilter.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/jwt/JwtTokenUtil.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/oauth/OAuthService.java
Labels: ✨ Feat, 🌱 BE

#44 [FE] 페이지 라우팅 수정
  front-end/src/App.tsx
  front-end/src/pages/home/Home.tsx
  front-end/src/pages/home/index.tsx
  front-end/src/pages/professor/course/classroom/index.tsx
  front-end/src/pages/professor/course/index.tsx
  front-end/src/pages/professor/home/index.tsx
  front-end/src/pages/professor/home/layout.tsx
  front-end/src/pages/professor/home/search/index.tsx
  front-end/src/pages/professor/login/index.tsx
  front-end/src/pages/professor/longin/index.tsx
  front-end/src/pages/professor/profile/index.tsx
  front-end/src/pages/professor/register/index.tsx
  front-end/src/pages/professor/search/index.tsx
  front-end/src/pages/student/course/index.tsx
  front-end/src/pages/student/home/index.tsx
Labels: 🐞 Fix, ⚛️ FE

#52 [FE] reset css 수정
  front-end/src/index.css
Labels: 🐞 Fix, ⚛️ FE

#54 [BE] 백엔드 Swagger 연동 기능 추가
  back-end/reacton/build.gradle
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/StudentCourseController.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/professor/ProfessorController.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/question/QuestionController.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/request/RequestController.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/DTO/ExceptionResponse.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/DTO/SuccessResponse.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/exception/Controller/CustomErrorController.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/exception/Handler/GlobalExceptionHandler.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/exception/code/GlobalErrorCode.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/jwt/JwtAuthenticationFilter.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/oauth/OAuthController.java
Labels: ✨ Feat, 🌱 BE

#56 [BE] 백엔드 로그 출력 기능 추가
  back-end/reacton/src/main/java/com/softeer/reacton/domain/professor/ProfessorController.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/professor/ProfessorService.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/jwt/JwtAuthenticationFilter.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/jwt/JwtTokenUtil.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/oauth/OAuthController.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/oauth/OAuthService.java
Labels: ✨ Feat, 🌱 BE

#59 [FE] 교수 로그인 페이지 디자인 구현
  front-end/src/App.tsx
  front-end/src/pages/professor/ProfessorLayout.tsx
  front-end/src/pages/professor/login/ProfessorLogin.module.css
  front-end/src/pages/professor/login/ProfessorLogin.tsx
  front-end/src/pages/professor/login/assets/professor-login.svg
  front-end/src/pages/professor/login/components/GoogleLoginButton.module.css
  front-end/src/pages/professor/login/components/GoogleLoginButton.tsx
  front-end/src/pages/professor/login/components/Private20250121.module.css
  front-end/src/pages/professor/login/components/Private20250121.tsx
  front-end/src/pages/professor/login/index.tsx
Labels: ✨ Feat, ⚛️ FE

#62 [FE] Custom Modal Hook 구현
  front-end/src/hooks/useModal.ts
  front-end/src/pages/professor/login/ProfessorLogin.tsx
  front-end/src/pages/professor/login/components/Private20250121.module.css
Labels: ✨ Feat, ⚛️ FE

#60 [BE] 입력값에 대한 유효성 검증
  back-end/reacton/src/main/java/com/softeer/reacton/domain/professor/ProfessorController.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/professor/ProfessorService.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/DTO/ExceptionResponse.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/exception/Handler/GlobalExceptionHandler.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/exception/code/FileErrorCode.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/oauth/OAuthService.java
Labels: ✨ Feat, 🌱 BE

#65 [FE]컴포넌트 사이즈 단위 통일
  front-end/src/components/modal/AlertModal.module.css
  front-end/src/components/modal/FileUploadPopupModal.module.css
  front-end/src/components/modal/PopupModal.module.css
Labels: 🐞 Fix, ⚛️ FE

#67 [FE]교수 로그인 페이지 모달 버블링 문제 해결
  front-end/src/pages/professor/login/components/Private20250121.tsx
Labels: 🐞 Fix, ⚛️ FE

#68 [FE] 교수 회원가입 페이지 구현
  front-end/src/App.tsx
  front-end/src/components/button/text/TextButton.module.css
  front-end/src/components/button/text/TextButton.tsx
  front-end/src/pages/professor/register/ProfessorRegister.module.css
  front-end/src/pages/professor/register/ProfessorRegister.tsx
  front-end/src/pages/professor/register/index.tsx
  front-end/src/utils/util.ts
Labels: ✨ Feat, ⚛️ FE

#69 [BE] 교수 수업 생성/수정/삭제 API
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/Course.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/ProfessorCourseController.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/ProfessorCourseService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/dto/CourseRequest.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/enums/CourseType.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/professor/Professor.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/schedule/Schedule.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/schedule/ScheduleRepository.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/DTO/SuccessResponse.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/dto/ExceptionResponse.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/dto/SuccessResponse.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/exception/Controller/CustomErrorController.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/exception/Handler/GlobalExceptionHandler.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/exception/code/CourseErrorCode.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/exception/code/ProfessorErrorCode.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/exception/code/TimeUtilErrorCode.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/jwt/JwtAuthenticationFilter.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/util/TimeUtil.java
Labels: ✨ Feat, 🌱 BE

#86 [FE] 교수 로그인 화면 이미지 변경
  front-end/src/pages/professor/login/ProfessorLogin.module.css
  front-end/src/pages/professor/login/ProfessorLogin.tsx
  front-end/src/pages/professor/login/assets/professor-login.png
  front-end/src/pages/professor/login/assets/professor-login.svg
Labels: 🐞 Fix, ⚛️ FE

#89 [FE] 학생 시작 페이지 구현
  front-end/src/App.tsx
  front-end/src/pages/student/components/StudentPopup.module.css
  front-end/src/pages/student/components/StudentPopup.tsx
  front-end/src/pages/student/home/StudentHome.module.css
  front-end/src/pages/student/home/StudentHome.tsx
  front-end/src/pages/student/home/components/ClassChip.module.css
  front-end/src/pages/student/home/components/ClassChip.tsx
  front-end/src/pages/student/home/components/ClassModal.module.css
  front-end/src/pages/student/home/components/ClassModal.tsx
  front-end/src/pages/student/home/index.tsx
Labels: ✨ Feat, ⚛️ FE

#84 [FE] DTO 및 레포지토리 작성
  front-end/src/core/errorType.ts
  front-end/src/core/model.ts
  front-end/src/core/repository.ts
  front-end/src/di.ts
  front-end/src/repository/authRepository.ts
  front-end/src/repository/classroomRepository.ts
  front-end/src/repository/courseRepository.ts
  front-end/src/repository/professorRepository.ts
  front-end/src/repository/repository.ts
Labels: ✨ Feat, ⚛️ FE

#91 [FE] 학생 강의 페이지 레이아웃 구현
  front-end/src/App.tsx
  front-end/src/pages/student/course/StudentCourse.module.css
  front-end/src/pages/student/course/StudentCourse.tsx
  front-end/src/pages/student/course/components/LayoutTab.module.css
  front-end/src/pages/student/course/components/LayoutTab.tsx
  front-end/src/pages/student/course/index.tsx
Labels: ✨ Feat, ⚛️ FE

#83 [BE] 입장 코드 중복시 재생성 로직 추가
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/ProfessorCourseService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/ProfessorCourseTransactionService.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/exception/code/CourseErrorCode.java
Labels: ✨ Feat, 🌱 BE

#90 [BE] 회원 탈퇴 및 로그아웃 API
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/Course.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/CourseRepository.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/professor/ProfessorController.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/professor/ProfessorService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/schedule/ScheduleRepository.java
Labels: ✨ Feat, 🌱 BE

#92 [BE] 학생 수업 조회 API 구현
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/Course.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/CourseRepository.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/StudentCourseController.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/StudentCourseService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/dto/CourseScheduleResponse.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/dto/CourseSummaryResponse.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/professor/ProfessorController.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/professor/ProfessorService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/schedule/ScheduleRepository.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/dto/SuccessResponse.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/exception/Controller/CustomErrorController.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/exception/Handler/GlobalExceptionHandler.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/exception/code/CourseErrorCode.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/jwt/JwtAuthenticationFilter.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/jwt/JwtTokenUtil.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/oauth/OAuthController.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/oauth/OAuthService.java
Labels: ✨ Feat, 🌱 BE

#93 [FE] 학생 요청하기 페이지 구현
  front-end/src/hooks/useBlockTimer.ts
  front-end/src/pages/student/course/StudentCourse.module.css
  front-end/src/pages/student/course/StudentCourse.tsx
  front-end/src/pages/student/course/components/LayoutTab.module.css
  front-end/src/pages/student/course/components/SuccessPopup.module.css
  front-end/src/pages/student/course/components/SuccessPopup.tsx
  front-end/src/pages/student/course/request/StudentRequest.module.css
  front-end/src/pages/student/course/request/StudentRequest.tsx
  front-end/src/pages/student/course/request/components/RequestCard.module.css
  front-end/src/pages/student/course/request/components/RequestCard.tsx
Labels: ✨ Feat, ⚛️ FE

#96 [FE] 스플릿 뷰 수정
  front-end/src/pages/student/components/StudentPopup.module.css
  front-end/src/pages/student/course/StudentCourse.module.css
  front-end/src/pages/student/course/components/LayoutTab.module.css
  front-end/src/pages/student/course/request/StudentRequest.module.css
  front-end/src/pages/student/course/request/components/RequestCard.module.css
  front-end/src/pages/student/home/StudentHome.module.css
  front-end/src/pages/student/home/components/ClassChip.module.css
  front-end/src/pages/student/home/components/ClassModal.module.css
Labels: 🔧 Chore, ⚛️ FE

#99 [FE] 교수 홈 페이지 구현
  front-end/src/App.tsx
  front-end/src/assets/icons/Search.svg
  front-end/src/components/button/icon/PaginationButton.module.css
  front-end/src/components/button/icon/PaginationButton.tsx
  front-end/src/components/button/text/TextButton.tsx
  front-end/src/components/chip/CategoryChip.module.css
  front-end/src/components/dropdown/DropDown.module.css
  front-end/src/components/dropdown/DropDown.tsx
  front-end/src/components/input/ModalInput.module.css
  front-end/src/components/input/ModalInput.tsx
  front-end/src/components/modal/AlertModal.tsx
  front-end/src/components/modal/FileUploadPopupModal.tsx
  front-end/src/components/modal/PopupModal.tsx
  front-end/src/core/errorType.ts
  front-end/src/hooks/useCountDown.ts
  front-end/src/hooks/useModal.ts
  front-end/src/hooks/usePagination.tsx
  front-end/src/pages/professor/ProfessorLayout.tsx
  front-end/src/pages/professor/home/ProfessorHome.module.css
  front-end/src/pages/professor/home/ProfessorHome.tsx
  front-end/src/pages/professor/home/assets/torus1.png
  front-end/src/pages/professor/home/assets/torus2.png
  front-end/src/pages/professor/home/components/CourseCard.module.css
  front-end/src/pages/professor/home/components/CourseCard.tsx
  front-end/src/pages/professor/home/components/FilterDropDown.module.css
  front-end/src/pages/professor/home/components/FilterDropDown.tsx
  front-end/src/pages/professor/home/components/MeatBallMenu.module.css
  front-end/src/pages/professor/home/components/MeatBallMenu.tsx
  front-end/src/pages/professor/home/components/TodayCourses.module.css
  front-end/src/pages/professor/home/components/TodayCourses.tsx
  front-end/src/pages/professor/home/components/TotalCourses.module.css
  front-end/src/pages/professor/home/components/TotalCourses.tsx
  front-end/src/pages/professor/home/index.tsx
  front-end/src/pages/professor/home/layout.tsx
  front-end/src/pages/professor/home/layout/ProfessorHomeLayout.module.css
  front-end/src/pages/professor/home/layout/ProfessorHomeLayout.tsx
  front-end/src/pages/professor/home/modal/CourseModal.module.css
  front-end/src/pages/professor/home/modal/CourseModal.tsx
  front-end/src/pages/professor/home/modal/components/TimeInput.module.css
  front-end/src/pages/professor/home/modal/components/TimeInput.tsx
  front-end/src/utils/util.ts
Labels: ✨ Feat, ⚛️ FE

#102 [FE] 교수 검색 페이지 구현
  front-end/src/App.tsx
  front-end/src/components/modal/AlertModal.module.css
  front-end/src/components/modal/FileUploadPopupModal.module.css
  front-end/src/components/modal/PopupModal.module.css
  front-end/src/pages/professor/home/ProfessorHome.tsx
  front-end/src/pages/professor/home/components/FilterDropDown.module.css
  front-end/src/pages/professor/home/components/MeatBallMenu.tsx
  front-end/src/pages/professor/home/layout/ProfessorHomeLayout.module.css
  front-end/src/pages/professor/home/layout/ProfessorHomeLayout.tsx
  front-end/src/pages/professor/home/search/ProfessorSearch.module.css
  front-end/src/pages/professor/home/search/ProfessorSearch.tsx
  front-end/src/pages/professor/home/search/index.tsx
  front-end/src/utils/courseAction.tsx
  front-end/src/utils/util.ts
Labels: ✨ Feat, ⚛️ FE

#105 [FE] 교수 프로필 페이지 구현
  front-end/src/App.tsx
  front-end/src/components/button/text/TextButton.module.css
  front-end/src/components/button/text/TextButton.tsx
  front-end/src/pages/professor/home/profile/ProfessorProfile.module.css
  front-end/src/pages/professor/home/profile/ProfessorProfile.tsx
  front-end/src/pages/professor/profile/index.tsx
Labels: ✨ Feat, ⚛️ FE

#108 [BE] 병합 과정에서 발생한 충돌 문제 해결
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/ProfessorCourseService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/StudentCourseService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/professor/ProfessorService.java
Labels: 🐞 Fix, 🌱 BE

#111 [BE] 수업 저장시 일정 데이터 저장 실패
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/Course.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/ProfessorCourseService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/ProfessorCourseTransactionService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/professor/ProfessorService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/question/QuestionRepository.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/request/RequestRepository.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/schedule/Schedule.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/schedule/ScheduleRepository.java
Labels: 🐞 Fix, 🌱 BE

#112 [FE] 학생 질문 페이지 구현
  front-end/index.html
  front-end/src/App.tsx
  front-end/src/core/model.ts
  front-end/src/pages/student/StudentLayout.tsx
  front-end/src/pages/student/course/StudentCourse.tsx
  front-end/src/pages/student/course/question/StudentQuestion.module.css
  front-end/src/pages/student/course/question/StudentQuestion.tsx
  front-end/src/pages/student/course/question/components/QuestionForm.module.css
  front-end/src/pages/student/course/question/components/QuestionForm.tsx
  front-end/src/pages/student/course/question/components/StudentMessage.module.css
  front-end/src/pages/student/course/question/components/StudentMessage.tsx
  front-end/src/repository/classroomRepository.ts
  front-end/vite.config.ts
Labels: ✨ Feat, ⚛️ FE

#117 [FE] 교수 페이지 관련 로직 추가
  front-end/src/App.tsx
  front-end/src/components/modal/ClassStartModal.module.css
  front-end/src/components/modal/ClassStartModal.tsx
  front-end/src/components/modal/FileUploadPopupModal.tsx
  front-end/src/hooks/useCountDown.ts
  front-end/src/hooks/useCourseAction.tsx
  front-end/src/pages/professor/home/ProfessorHome.module.css
  front-end/src/pages/professor/home/ProfessorHome.tsx
  front-end/src/pages/professor/home/components/CourseCard.module.css
  front-end/src/pages/professor/home/components/CourseCard.tsx
  front-end/src/pages/professor/home/components/FilterDropDown.tsx
  front-end/src/pages/professor/home/components/TodayCourses.module.css
  front-end/src/pages/professor/home/components/TodayCourses.tsx
  front-end/src/pages/professor/home/components/TotalCourses.tsx
  front-end/src/pages/professor/home/layout/ProfessorHomeLayout.tsx
  front-end/src/pages/professor/home/loading/ProfessorLoading.module.css
  front-end/src/pages/professor/home/loading/ProfessorLoading.tsx
  front-end/src/pages/professor/home/profile/ProfessorProfile.tsx
  front-end/src/pages/professor/home/search/ProfessorSearch.tsx
  front-end/src/pages/professor/login/ProfessorLogin.tsx
  front-end/src/pages/professor/register/ProfessorRegister.tsx
  front-end/src/repository/courseRepository.ts
  front-end/src/utils/util.ts
Labels: ✨ Feat, ⚛️ FE

#104 [BE] Dockerfile 추가
  back-end/reacton/Dockerfile
Labels: 🔧 Chore, 🌱 BE

#113 [BE] 교수 전체 수업 조회 API 중 '오늘 수업 가져오기'의 정렬 방식 수정
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/ProfessorCourseService.java
Labels: ✨ Feat, 🌱 BE

#121 [FE] import alias 추가
  front-end/package-lock.json
  front-end/package.json
  front-end/src/components/button/icon/AddDeleteButton.tsx
  front-end/src/components/button/icon/CheckButton.tsx
  front-end/src/components/button/icon/CircleAddButton.tsx
  front-end/src/components/button/icon/CircleBackButton.tsx
  front-end/src/components/button/icon/PaginationButton.tsx
  front-end/src/components/button/icon/RecIconButton.tsx
  front-end/src/components/button/icon/ZoomButton.tsx
  front-end/src/components/dropdown/DropDown.tsx
  front-end/src/components/modal/AlertModal.tsx
  front-end/src/components/modal/ClassStartModal.tsx
  front-end/src/components/modal/FileUploadPopupModal.tsx
  front-end/src/components/modal/PopupModal.tsx
  front-end/src/hooks/useCountDown.ts
  front-end/src/hooks/useCourseAction.tsx
  front-end/src/pages/professor/home/ProfessorHome.tsx
  front-end/src/pages/professor/home/components/CourseCard.tsx
  front-end/src/pages/professor/home/components/FilterDropDown.tsx
  front-end/src/pages/professor/home/components/MeatBallMenu.tsx
  front-end/src/pages/professor/home/components/TodayCourses.tsx
  front-end/src/pages/professor/home/components/TotalCourses.tsx
  front-end/src/pages/professor/home/layout/ProfessorHomeLayout.tsx
  front-end/src/pages/professor/home/loading/ProfessorLoading.tsx
  front-end/src/pages/professor/home/modal/CourseModal.tsx
  front-end/src/pages/professor/home/profile/ProfessorProfile.tsx
  front-end/src/pages/professor/home/search/ProfessorSearch.tsx
  front-end/src/pages/professor/login/ProfessorLogin.tsx
  front-end/src/pages/professor/login/components/Private20250121.tsx
  front-end/src/pages/professor/register/ProfessorRegister.tsx
  front-end/src/pages/student/components/StudentPopup.tsx
  front-end/src/pages/student/course/StudentCourse.tsx
  front-end/src/pages/student/course/question/StudentQuestion.tsx
  front-end/src/pages/student/course/question/components/StudentMessage.tsx
  front-end/src/pages/student/course/react/StudentReact.tsx
  front-end/src/pages/student/course/react/components/ReactCard.tsx
  front-end/src/pages/student/course/request/StudentRequest.tsx
  front-end/src/pages/student/course/request/components/RequestCard.tsx
  front-end/src/pages/student/home/StudentHome.tsx
  front-end/src/pages/student/home/components/ClassModal.tsx
  front-end/src/repository/classroomRepository.ts
  front-end/src/repository/courseRepository.ts
  front-end/src/repository/professorRepository.ts
  front-end/src/utils/util.ts
  front-end/tsconfig.app.json
  front-end/vite.config.ts
Labels: ⚛️ FE, ⚙ Setting

#126 [FE] 교수 페이지 오류 수정
  front-end/src/App.tsx
  front-end/src/pages/home/Home.module.css
  front-end/src/pages/home/Home.tsx
  front-end/src/pages/home/index.tsx
  front-end/src/pages/professor/login/ProfessorLogin.tsx
  front-end/src/pages/professor/register/ProfessorRegister.tsx
Labels: 🐞 Fix, ⚛️ FE

#120 [BE] 수업 질문방 서버 관련 프로젝트 생성
  back-end/reacton-classroom/.gitignore
  back-end/reacton-classroom/build.gradle
  back-end/reacton-classroom/gradle/wrapper/gradle-wrapper.jar
  back-end/reacton-classroom/gradle/wrapper/gradle-wrapper.properties
  back-end/reacton-classroom/gradlew
  back-end/reacton-classroom/gradlew.bat
  back-end/reacton-classroom/settings.gradle
  back-end/reacton-classroom/src/main/java/com/softeer/reacton_classroom/ReactonClassroomApplication.java
  back-end/reacton-classroom/src/main/main.iml
  back-end/reacton-classroom/src/test/java/com/softeer/reacton_classroom/ReactonClassroomApplicationTests.java
  back-end/reacton-classroom/src/test/test.iml
Labels: 🌱 BE, ⚙ Setting

#129 [FE] 학생 홈 입장코드 fetch 구현
  front-end/src/App.tsx
  front-end/src/core/errorType.ts
  front-end/src/core/model.ts
  front-end/src/hooks/useModal.ts
  front-end/src/pages/student/course/StudentCourse.module.css
  front-end/src/pages/student/home/StudentHome.tsx
  front-end/src/pages/student/home/components/ClassModal.tsx
  front-end/src/repository/courseRepository.ts
Labels: ✨ Feat, ⚛️ FE

#132 [FE] 교수 강의 상세 정보 페이지 구현
  front-end/src/App.tsx
  front-end/src/pages/professor/course/ProfessorCourse.module.css
  front-end/src/pages/professor/course/ProfessorCourse.tsx
  front-end/src/pages/professor/course/components/CourseQuestion.module.css
  front-end/src/pages/professor/course/components/CourseQuestion.tsx
  front-end/src/pages/professor/course/components/CourseRequest.module.css
  front-end/src/pages/professor/course/components/CourseRequest.tsx
  front-end/src/pages/professor/course/components/QuestionPage.module.css
  front-end/src/pages/professor/course/components/QuestionPage.tsx
  front-end/src/pages/professor/course/components/RequestBar.module.css
  front-end/src/pages/professor/course/components/RequestBar.tsx
  front-end/src/pages/professor/course/index.tsx
  front-end/src/pages/professor/home/components/CourseCard.tsx
  front-end/src/utils/util.ts
Labels: ✨ Feat, ⚛️ FE

#133 [FE] 강의 상세 페이지 요청 통계 하이라이트 변경
  front-end/src/pages/professor/course/components/CourseRequest.tsx
  front-end/src/pages/professor/course/components/RequestBar.tsx
Labels: ✨ Feat, ⚛️ FE

#140 [FE] 로컬 도메인 세팅
  front-end/.gitignore
  front-end/vite.config.ts
Labels: ⚛️ FE, ⚙ Setting

#142 [FE] 실시간 수업 응답하기 컴포넌트 구현
  front-end/src/pages/professor/course/classroom/components/RequestBox.module.css
  front-end/src/pages/professor/course/classroom/components/RequestBox.tsx
  front-end/src/pages/professor/course/classroom/components/RequestCard.module.css
  front-end/src/pages/professor/course/classroom/components/RequestCard.tsx
Labels: ✨ Feat, ⚛️ FE

#144 [FE] 강의 입장코드 모달 컴포넌트 구현
  front-end/src/pages/professor/course/classroom/components/AccessCodeModal.module.css
  front-end/src/pages/professor/course/classroom/components/AccessCodeModal.tsx
Labels: ✨ Feat, ⚛️ FE

#135 [BE] SSE를 활용한 실시간 질문 및 요청 처리 구현 - 김선오
  back-end/reacton-classroom/src/main/java/com/softeer/reacton_classroom/domain/sse/controller/SseConnectionController.java
  back-end/reacton-classroom/src/main/java/com/softeer/reacton_classroom/domain/sse/controller/SseMessageController.java
  back-end/reacton-classroom/src/main/java/com/softeer/reacton_classroom/domain/sse/dto/MessageResponse.java
  back-end/reacton-classroom/src/main/java/com/softeer/reacton_classroom/domain/sse/service/SseService.java
  back-end/reacton-classroom/src/main/java/com/softeer/reacton_classroom/global/dto/ExceptionResponse.java
  back-end/reacton-classroom/src/main/java/com/softeer/reacton_classroom/global/dto/SuccessResponse.java
  back-end/reacton-classroom/src/main/java/com/softeer/reacton_classroom/global/exception/BaseException.java
  back-end/reacton-classroom/src/main/java/com/softeer/reacton_classroom/global/exception/code/ErrorCode.java
  back-end/reacton-classroom/src/main/java/com/softeer/reacton_classroom/global/exception/code/GlobalErrorCode.java
  back-end/reacton-classroom/src/main/java/com/softeer/reacton_classroom/global/exception/code/SseErrorCode.java
  back-end/reacton-classroom/src/main/java/com/softeer/reacton_classroom/global/exception/controller/CustomErrorController.java
  back-end/reacton-classroom/src/main/java/com/softeer/reacton_classroom/global/exception/handler/GlobalExceptionHandler.java
Labels: ✨ Feat, 🌱 BE

#146 [FE] 반응 통계 모달 구현
  front-end/src/pages/professor/course/classroom/assets/particle.png
  front-end/src/pages/professor/course/classroom/components/ReactionModal.module.css
  front-end/src/pages/professor/course/classroom/components/ReactionModal.tsx
Labels: ✨ Feat, ⚛️ FE

#138 [BE] 리다이렉트시 쿠키 삭제되는 문제
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/ProfessorCourseController.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/professor/ProfessorController.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/config/CookieConfig.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/jwt/JwtAuthenticationFilter.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/oauth/OAuthController.java
Labels: 🐞 Fix, 🌱 BE

#151 [FE] PDF Viewer 커스텀 훅 구현
  front-end/package-lock.json
  front-end/package.json
  front-end/src/hooks/usePDF.ts
  front-end/src/pages/professor/course/classroom/components/PDFViewer.module.css
  front-end/src/pages/professor/course/classroom/components/PDFViewer.tsx
Labels: ✨ Feat, ⚛️ FE

#156 [FE] authRepository 연동
  front-end/src/pages/professor/login/ProfessorLogin.tsx
  front-end/src/repository/authRepository.ts
Labels: ✨ Feat, ⚛️ FE

#148 [BE] S3를 활용한 파일 관련 API
  back-end/reacton/build.gradle
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/Course.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/ProfessorCourseController.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/ProfessorCourseService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/dto/CourseDetailResponse.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/dto/CourseSummaryResponse.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/professor/Professor.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/professor/ProfessorController.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/professor/ProfessorRepository.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/professor/ProfessorService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/professor/dto/ProfessorInfoResponse.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/dto/SuccessResponse.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/exception/Handler/GlobalExceptionHandler.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/exception/Handler/S3ExceptionHandler.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/exception/code/FileErrorCode.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/exception/code/S3ErrorCode.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/s3/S3Config.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/s3/S3Service.java
Labels: ✨ Feat, 🌱 BE

#158 [BE] 구글 로그인시 계정 선택 가능하도록 수정
  back-end/reacton/src/main/java/com/softeer/reacton/global/oauth/OAuthConfig.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/oauth/OAuthProvider.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/oauth/OAuthService.java
Labels: ✨ Feat, 🌱 BE

#162 [BE] 이미지 파일 조회시 presigned-url 발급
  back-end/reacton/src/main/java/com/softeer/reacton/domain/professor/ProfessorService.java
Labels: ✨ Feat, 🌱 BE

#169 [FE] 교수 사용자 관련 API 연동
  front-end/src/components/dropdown/DropDown.module.css
  front-end/src/components/modal/AlertModal.tsx
  front-end/src/components/modal/FileUploadPopupModal.tsx
  front-end/src/components/modal/PopupModal.tsx
  front-end/src/pages/home/Home.module.css
  front-end/src/pages/professor/course/ProfessorCourse.tsx
  front-end/src/pages/professor/home/components/FilterDropDown.module.css
  front-end/src/pages/professor/home/layout/ProfessorHomeLayout.tsx
  front-end/src/pages/professor/home/profile/ProfessorProfile.module.css
  front-end/src/pages/professor/home/profile/ProfessorProfile.tsx
  front-end/src/pages/professor/register/ProfessorRegister.tsx
  front-end/src/repository/professorRepository.ts
  front-end/src/utils/util.ts
Labels: ✨ Feat, ⚛️ FE

#168 [FE] 교수 pdf 페이지 구현
  front-end/src/App.tsx
  front-end/src/core/model.ts
  front-end/src/hooks/usePDF.ts
  front-end/src/pages/professor/course/classroom/ProfessorClassroom.module.css
  front-end/src/pages/professor/course/classroom/ProfessorClassroom.tsx
  front-end/src/pages/professor/course/classroom/components/AccessCodeModal.tsx
  front-end/src/pages/professor/course/classroom/components/PDFMainComponent.module.css
  front-end/src/pages/professor/course/classroom/components/PDFMainComponent.tsx
  front-end/src/pages/professor/course/classroom/components/PDFSideBar.tsx
  front-end/src/pages/professor/course/classroom/components/PDFSidebar.module.css
  front-end/src/pages/professor/course/classroom/components/question/QuestionBoard.tsx
  front-end/src/pages/professor/course/classroom/components/question/QuestionCard.module.css
  front-end/src/pages/professor/course/classroom/components/question/QuestionModal.module.css
  front-end/src/pages/professor/course/classroom/components/question/QuestionModal.tsx
  front-end/src/pages/professor/course/classroom/components/reaction/EmojiCounter.tsx
  front-end/src/pages/professor/course/classroom/components/reaction/ReactionIcon.tsx
  front-end/src/pages/student/course/StudentCourse.tsx
  front-end/src/pages/student/course/question/StudentQuestion.tsx
  front-end/src/pages/student/course/react/StudentReact.tsx
  front-end/src/pages/student/course/request/StudentRequest.tsx
  front-end/src/repository/classroomRepository.ts
  front-end/src/repository/courseRepository.ts
  front-end/src/repository/professorRepository.ts
Labels: ✨ Feat, ⚛️ FE

#175 [FE] 레포지토리 에러 생성 분리
  front-end/src/repository/professorRepository.ts
  front-end/src/repository/throwError.ts
Labels: 🔨 Refactor, ⚛️ FE

#177 [FE] 요청하기 모델 수정
  front-end/src/core/model.ts
Labels: 🔧 Chore, ⚛️ FE

#178 [FE] CourseRepository 로직 구현
  front-end/src/core/model.ts
  front-end/src/repository/courseRepository.ts
Labels: ✨ Feat, ⚛️ FE

#179 [BE] reacton-classroom CI/CD 구축
  .github/workflows/reacton-ci-cd.yml
  back-end/reacton-classroom/Dockerfile
Labels: 🔧 Chore, 🌱 BE

#174 [BE] 학생 메시지 전송 API 구현
  back-end/reacton-classroom/src/main/java/com/softeer/reacton_classroom/domain/sse/controller/SseConnectionController.java
  back-end/reacton-classroom/src/main/java/com/softeer/reacton_classroom/domain/sse/controller/SseMessageController.java
  back-end/reacton-classroom/src/main/java/com/softeer/reacton_classroom/domain/sse/dto/MessageResponse.java
  back-end/reacton-classroom/src/main/java/com/softeer/reacton_classroom/domain/sse/service/SseService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/classroom/StudentClassroomController.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/classroom/StudentClassroomService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/ProfessorCourseController.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/ProfessorCourseService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/ProfessorCourseTransactionService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/question/Question.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/question/StudentQuestionController.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/question/StudentQuestionService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/question/dto/QuestionAllResponse.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/question/dto/QuestionSendRequest.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/reaction/StudentReactionController.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/reaction/StudentReactionService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/reaction/dto/ReactionSendRequest.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/reaction/dto/ReactionSseRequest.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/request/Request.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/request/RequestConstants.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/request/RequestController.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/request/RequestRepository.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/request/StudentRequestController.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/request/StudentRequestService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/request/dto/RequestSendRequest.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/request/dto/RequestSseRequest.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/dto/SuccessResponse.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/exception/code/RequestErrorCode.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/exception/code/SseErrorCode.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/jwt/JwtAuthenticationFilter.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/sse/SseMessageSender.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/sse/dto/SseMessage.java
Labels: ✨ Feat, 🌱 BE

#181 [BE] Merge 과정에서 발생한 충돌 문제 해결
  back-end/reacton/src/main/java/com/softeer/reacton/global/dto/SuccessResponse.java
Labels: 🐞 Fix, 🌱 BE

#183 [FE] 학생 수업 참가 요청 API 구현
  front-end/src/pages/student/home/StudentHome.tsx
  front-end/src/repository/classroomRepository.ts
  front-end/src/utils/studentPopupUtils.tsx
Labels: ✨ Feat, ⚛️ FE

#185 [FE] 페이지 에러 처리 분리
  front-end/src/pages/professor/course/ProfessorCourse.tsx
  front-end/src/pages/professor/course/components/CourseRequest.tsx
  front-end/src/pages/professor/home/ProfessorHome.tsx
  front-end/src/pages/professor/home/components/CourseCard.tsx
  front-end/src/pages/professor/home/layout/ProfessorHomeLayout.tsx
  front-end/src/pages/professor/home/loading/ProfessorLoading.tsx
  front-end/src/pages/professor/home/profile/ProfessorProfile.tsx
  front-end/src/pages/professor/home/search/ProfessorSearch.tsx
  front-end/src/pages/professor/register/ProfessorRegister.tsx
  front-end/src/repository/courseRepository.ts
  front-end/src/utils/courseAction.tsx
  front-end/src/utils/professorError.tsx
Labels: ✨ Feat, ⚛️ FE

#188 [BE] 질문 체크 기능 구현
  back-end/reacton-classroom/src/main/java/com/softeer/reacton_classroom/domain/sse/controller/SseMessageController.java
  back-end/reacton-classroom/src/main/java/com/softeer/reacton_classroom/domain/sse/service/SseService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/StudentCourseController.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/question/ProfessorQuestionController.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/question/ProfessorQuestionService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/question/Question.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/question/QuestionRepository.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/question/QuestionService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/question/StudentQuestionController.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/question/StudentQuestionService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/question/dto/QuestionCheckSseRequest.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/reaction/StudentReactionService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/request/StudentRequestService.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/exception/code/QuestionErrorCode.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/sse/SseMessageSender.java
Labels: ✨ Feat, 🌱 BE

#195 [FE] 에러 처리 반영 및 API 추가 연동
  front-end/src/App.tsx
  front-end/src/pages/professor/course/ProfessorCourse.tsx
  front-end/src/pages/professor/home/ProfessorHome.tsx
  front-end/src/pages/professor/home/layout/ProfessorHomeLayout.tsx
  front-end/src/pages/professor/home/modal/CourseModal.tsx
  front-end/src/pages/professor/home/profile/ProfessorProfile.tsx
  front-end/src/pages/professor/home/search/ProfessorSearch.tsx
  front-end/src/pages/professor/loading/ProfessorLoading.module.css
  front-end/src/pages/professor/loading/ProfessorLoading.tsx
  front-end/src/pages/professor/register/ProfessorRegister.tsx
  front-end/src/repository/courseRepository.ts
  front-end/src/utils/courseAction.tsx
  front-end/src/utils/professorError.tsx
  front-end/src/utils/util.ts
Labels: ✨ Feat, ⚛️ FE

#189 [BE] 교수 수업 종료 시 학생에게 알리는 기능 추가
  back-end/reacton-classroom/build.gradle
  back-end/reacton-classroom/src/main/java/com/softeer/reacton_classroom/domain/sse/controller/SseConnectionController.java
  back-end/reacton-classroom/src/main/java/com/softeer/reacton_classroom/domain/sse/controller/SseMessageController.java
  back-end/reacton-classroom/src/main/java/com/softeer/reacton_classroom/domain/sse/service/SseService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/ProfessorCourseService.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/sse/SseMessageSender.java
Labels: ✨ Feat, 🌱 BE

#199 [BE] merge 과정에서 발생한 버그 해결 #198
  back-end/reacton/src/main/java/com/softeer/reacton/global/sse/SseMessageSender.java
Labels: 🐞 Fix, 🌱 BE

#201 [BE] SSE 연결 성공 시 초기 메시지가 전송되지 않는 문제 해결
  back-end/reacton-classroom/src/main/java/com/softeer/reacton_classroom/domain/sse/service/SseService.java
Labels: 🐞 Fix, 🌱 BE

#190 [BE] 수업 검색 기능 추가
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/CourseRepository.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/ProfessorCourseController.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/ProfessorCourseService.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/dto/SuccessResponse.java
Labels: ✨ Feat, 🌱 BE

#197 [BE] 회원 탈퇴시 파일 값 존재 여부 확인 후 S3에 삭제 요청 전송
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/CourseRepository.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/professor/ProfessorService.java
Labels: 🐞 Fix, 🌱 BE

#194 [BE] 활성화된 수업 조회시 응답 데이터 추가
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/ProfessorCourseController.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/ProfessorCourseService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/dto/ActiveCourseResponse.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/dto/SuccessResponse.java
Labels: ✨ Feat, 🌱 BE

#206 [BE] 질문 데이터를 조회&삭제하는 과정에서 발생하는 문제 해결
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/ProfessorCourseService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/question/QuestionRepository.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/question/StudentQuestionService.java
Labels: 🐞 Fix, 🌱 BE

#207 [BE] 질문 데이터를 조회&삭제하는 과정에서 발생하는 문제 해결
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/ProfessorCourseService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/question/QuestionRepository.java
Labels: 🐞 Fix, 🌱 BE

#209 [FE] 학생 SSE 연결 및 기능 구현
  front-end/src/pages/student/course/StudentCourse.tsx
  front-end/src/pages/student/course/question/StudentQuestion.tsx
  front-end/src/pages/student/home/StudentHome.tsx
  front-end/src/utils/studentPopupUtils.tsx
Labels: ✨ Feat, ⚛️ FE

#211 [FE] 교수 실시간 페이지 SSE 연동
  front-end/src/pages/professor/course/classroom/ProfessorClassroom.tsx
  front-end/src/pages/professor/course/classroom/components/PDFMainComponent.tsx
  front-end/src/pages/professor/course/classroom/components/RequestBox.tsx
  front-end/src/pages/professor/course/classroom/components/reaction/EmojiCounter.tsx
  front-end/src/repository/classroomRepository.ts
  front-end/src/repository/courseRepository.ts
  front-end/src/utils/courseAction.tsx
Labels: ✨ Feat, ⚛️ FE

#214 [FE] 교수 유저 데이터 캐싱 추가
  front-end/src/repository/professorRepository.ts
Labels: ✨ Feat, ⚛️ FE

#215 [FE] 학생 반응하기 요청하기 로컬 스토리지 저장 기능 구현
  front-end/src/hooks/useBlockTimer.ts
  front-end/src/pages/student/course/react/StudentReact.tsx
  front-end/src/pages/student/course/react/components/ReactCard.tsx
  front-end/src/pages/student/course/request/StudentRequest.tsx
  front-end/src/pages/student/course/request/components/RequestCard.tsx
  front-end/src/repository/classroomRepository.ts
Labels: ✨ Feat, ⚛️ FE

#223 [FE] 학생 페이지 UI 버그
  front-end/src/pages/home/Home.module.css
  front-end/src/pages/home/Home.tsx
  front-end/src/pages/student/StudentLayout.tsx
  front-end/src/pages/student/course/StudentCourse.module.css
  front-end/src/pages/student/course/StudentCourse.tsx
  front-end/src/pages/student/course/question/StudentQuestion.module.css
  front-end/src/pages/student/home/StudentHome.module.css
  front-end/src/pages/student/home/StudentHome.tsx
  front-end/src/repository/classroomRepository.ts
  front-end/src/utils/studentPopupUtils.tsx
  front-end/src/utils/util.ts
Labels: 🐞 Fix, ⚛️ FE

#225 [FE] 교수 UI 오류 수정
  front-end/src/components/button/icon/AddDeleteButton.tsx
  front-end/src/components/input/ModalInput.module.css
  front-end/src/components/input/ModalInput.tsx
  front-end/src/components/modal/ClassStartModal.module.css
  front-end/src/components/modal/ClassStartModal.tsx
  front-end/src/components/modal/FileUploadPopupModal.module.css
  front-end/src/components/modal/FileUploadPopupModal.tsx
  front-end/src/hooks/useModal.ts
  front-end/src/pages/professor/ProfessorLayout.tsx
  front-end/src/pages/professor/course/ProfessorCourse.tsx
  front-end/src/pages/professor/course/classroom/ProfessorClassroom.tsx
  front-end/src/pages/professor/course/classroom/components/PDFMainComponent.tsx
  front-end/src/pages/professor/course/classroom/components/question/QuestionBoard.tsx
  front-end/src/pages/professor/course/classroom/components/question/QuestionModal.tsx
  front-end/src/pages/professor/home/ProfessorHome.module.css
  front-end/src/pages/professor/home/ProfessorHome.tsx
  front-end/src/pages/professor/home/components/CourseCard.module.css
  front-end/src/pages/professor/home/components/TodayCourses.module.css
  front-end/src/pages/professor/home/layout/ProfessorHomeLayout.tsx
  front-end/src/pages/professor/home/modal/CourseModal.module.css
  front-end/src/pages/professor/home/modal/CourseModal.tsx
  front-end/src/pages/professor/home/modal/components/TimeInput.tsx
  front-end/src/pages/professor/home/profile/ProfessorProfile.tsx
  front-end/src/pages/professor/home/search/ProfessorSearch.tsx
  front-end/src/pages/professor/loading/ProfessorLoading.tsx
  front-end/src/pages/professor/professorError.tsx
  front-end/src/pages/professor/register/ProfessorRegister.tsx
  front-end/src/utils/courseAction.tsx
  front-end/src/vite-env.d.ts
Labels: 🐞 Fix, ⚛️ FE

#218 [BE] 질문 체크 기능 개선
  back-end/reacton/src/main/java/com/softeer/reacton/domain/question/ProfessorQuestionService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/question/QuestionRepository.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/question/QuestionService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/question/StudentQuestionController.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/question/StudentQuestionService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/request/RequestRepository.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/request/RequestService.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/request/StudentRequestService.java
Labels: 🐞 Fix, 🌱 BE

#208 [BE] 수업 검색 기능 추가
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/ProfessorCourseService.java
Labels: 🔨 Refactor, 🌱 BE

#227 [FE] react-lazy를 활용한 초기 렌더링 개선
  front-end/src/App.tsx
  front-end/src/pages/loading/Loading.module.css
  front-end/src/pages/loading/Loading.tsx
  front-end/src/pages/professor/loading/ProfessorLoading.module.css
  front-end/src/pages/professor/loading/ProfessorLoading.tsx
Labels: ✨ Feat, ⚛️ FE

#234 [FE] 교수 프로필 페이지 레이아웃 오류 수정
  front-end/src/pages/professor/home/profile/ProfessorProfile.module.css
Labels: 🐞 Fix, ⚛️ FE

#237 [FE] 배포 시 프록지 미적용 문제 해결
  front-end/src/pages/professor/course/classroom/ProfessorClassroom.tsx
  front-end/src/pages/student/course/StudentCourse.tsx
  front-end/src/repository/classroomRepository.ts
  front-end/src/repository/courseRepository.ts
  front-end/src/repository/professorRepository.ts
Labels: 🐞 Fix, ⚛️ FE

#235 [FE] useTemporaryState custom hook 구현
  front-end/src/hooks/customHook.ts
  front-end/src/hooks/useTemporaryState.ts
  front-end/src/pages/student/course/react/components/ReactCard.module.css
  front-end/src/pages/student/course/react/components/ReactCard.tsx
  front-end/src/pages/student/course/request/components/RequestCard.module.css
  front-end/src/pages/student/course/request/components/RequestCard.tsx
Labels: ✨ Feat, ⚛️ FE

#241 [FE] 수업 종료시 통계 모달 연동
  front-end/src/pages/professor/course/classroom/ProfessorClassroom.tsx
Labels: ✨ Feat, ⚛️ FE

#243 [FE] 배포 환경 세팅
  front-end/.devcontainer/devcontainer.json
  front-end/.devcontainer/nginx.conf
  front-end/.devcontainer/run-nginx
  front-end/index.html
  front-end/src/pages/professor/ProfessorLayout.tsx
  front-end/src/pages/professor/course/classroom/components/PDFMainComponent.tsx
  front-end/src/pages/professor/course/classroom/components/ReactionModal.tsx
  front-end/src/pages/professor/home/modal/CourseModal.tsx
  front-end/src/pages/professor/loading/ProfessorLoading.tsx
  front-end/src/pages/professor/professorError.tsx
  front-end/src/repository/classroomRepository.ts
  front-end/src/repository/courseRepository.ts
  front-end/src/repository/professorRepository.ts
  front-end/src/utils/courseAction.tsx
  front-end/src/vite-env.d.ts
  front-end/vite.config.ts
Labels: ⚛️ FE, ⚙ Setting

#232 [BE] 숫자 관련 오버플로우에 대한 예외 처리
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/Course.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/dto/CourseRequest.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/request/RequestService.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/exception/code/RequestErrorCode.java
Labels: 🐞 Fix, 🌱 BE

#245 [FE] 학생 레이아웃 크기에 따라 조절
  front-end/src/App.tsx
  front-end/src/pages/student/StudentLayout.tsx
  front-end/src/pages/student/components/StudentPopup.module.css
  front-end/src/pages/student/course/StudentCourse.module.css
  front-end/src/pages/student/course/components/LayoutTab.module.css
  front-end/src/pages/student/course/components/SuccessPopup.tsx
  front-end/src/pages/student/course/question/StudentQuestion.module.css
  front-end/src/pages/student/course/question/StudentQuestion.tsx
  front-end/src/pages/student/course/question/components/QuestionForm.module.css
  front-end/src/pages/student/course/question/components/StudentMessage.module.css
  front-end/src/pages/student/course/react/StudentReact.module.css
  front-end/src/pages/student/course/react/StudentReact.tsx
  front-end/src/pages/student/course/react/components/ReactCard.module.css
  front-end/src/pages/student/course/request/StudentRequest.module.css
  front-end/src/pages/student/course/request/StudentRequest.tsx
  front-end/src/pages/student/course/request/components/RequestCard.module.css
  front-end/src/pages/student/home/StudentHome.module.css
Labels: 🐞 Fix, ⚛️ FE

#246 [FE] 배포 스크립트 작성
  front-end/.devcontainer/nginx.conf
  front-end/.gitignore
  front-end/publish
Labels: ⚛️ FE, ⚙ Setting

#249 수업 생성시 입장 코드 6자리로 고정
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/ProfessorCourseService.java
Labels: 🐞 Fix, 🌱 BE

#252 학생 SSE connection 부하 개선
  back-end/reacton-classroom/src/main/java/com/softeer/reacton_classroom/domain/sse/service/SseService.java
Labels: 🐞 Fix, 🌱 BE

#250 [BE] 오늘 수업 수정 시 오늘 날짜에 해당하는 Schedule만 표기되는 문제 해결
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/ProfessorCourseService.java
Labels: 🐞 Fix, 🌱 BE

#256 [FE] UI 버그 수정
  front-end/copyCmaps.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/components/input/ModalInput.tsx
  front-end/src/hooks/usePDF.ts
  front-end/src/index.css
  front-end/src/pages/loading/Loading.module.css
  front-end/src/pages/professor/ProfessorLayout.tsx
  front-end/src/pages/professor/course/classroom/ProfessorClassroom.tsx
  front-end/src/pages/professor/course/classroom/components/PDFSideBar.tsx
  front-end/src/pages/professor/course/classroom/components/question/QuestionModal.tsx
  front-end/src/pages/professor/home/components/CourseCard.tsx
  front-end/src/pages/professor/home/components/FilterDropDown.tsx
  front-end/src/pages/professor/home/modal/CourseModal.tsx
  front-end/src/pages/professor/home/modal/components/TimeInput.tsx
  front-end/src/pages/professor/home/profile/ProfessorProfile.tsx
  front-end/src/pages/professor/home/search/ProfessorSearch.module.css
  front-end/src/pages/professor/professorError.tsx
  front-end/src/repository/classroomRepository.ts
  front-end/src/repository/courseRepository.ts
  front-end/src/repository/professorRepository.ts
Labels: 🐞 Fix, ⚛️ FE

#258 [FE] 자동 번역 오류 수정
  front-end/index.html
Labels: 🐞 Fix, ⚛️ FE

#260 [FE] 모바일 뷰 레이아웃 조정
  front-end/src/App.tsx
  front-end/src/pages/student/StudentLayout.tsx
  front-end/src/pages/student/course/request/StudentRequest.module.css
Labels: 🐞 Fix, ⚛️ FE

#264 [FE] 수업 유효성 항목 추가
  front-end/src/pages/professor/home/components/CourseCard.module.css
  front-end/src/pages/professor/home/modal/CourseModal.tsx
Labels: 🐞 Fix, ⚛️ FE

#262 [BE] 수업 생성시 유효성 검사 누락으로 인한 입장 코드 재생성
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/dto/CourseRequest.java
Labels: 🐞 Fix, 🌱 BE

#267 [FE] 파일 삭제 기능 추가
  front-end/src/components/modal/FileUploadPopupModal.tsx
  front-end/src/repository/courseRepository.ts
  front-end/src/utils/courseAction.tsx
Labels: 🐞 Fix, ⚛️ FE

#269 [FE] 수업 삭제 시 홈 화면으로 이동 추가
  front-end/src/utils/courseAction.tsx
Labels: 🐞 Fix, ⚛️ FE

#271 [FE] 교수 검색 키워드 encode
  front-end/src/pages/professor/home/layout/ProfessorHomeLayout.tsx
  front-end/src/repository/courseRepository.ts
Labels: 🐞 Fix, ⚛️ FE

#265 [BE] SSE connection 부하 문제 개선
  back-end/reacton-classroom/src/main/java/com/softeer/reacton_classroom/domain/sse/service/SseService.java
  back-end/reacton-classroom/src/main/java/com/softeer/reacton_classroom/global/exception/code/SseErrorCode.java
Labels: 🐞 Fix, 🌱 BE

#275 [FE] vercel.json에 백엔드 API 추가하도록 수정
  front-end/.gitignore
  front-end/package.json
  front-end/vercelPrebuild.js
Labels: 🐞 Fix, ⚛️ FE, ⚙ Setting

#273 [BE] 학생과 교수의 access token이 겹치는 문제 해결
  back-end/reacton-classroom/src/main/java/com/softeer/reacton_classroom/global/jwt/JwtAuthenticationFilter.java
  back-end/reacton/src/main/java/com/softeer/reacton/domain/course/StudentCourseController.java
  back-end/reacton/src/main/java/com/softeer/reacton/global/jwt/JwtAuthenticationFilter.java
Labels: 🐞 Fix, 🌱 BE

#279 [FE] 강의 일정 관련 버그 수정
  front-end/.gitignore
  front-end/package.json
  front-end/src/pages/professor/home/modal/CourseModal.tsx
  front-end/src/pages/professor/home/modal/components/TimeInput.tsx
  front-end/vercel.json
  front-end/vercelRewrite.js
Labels: 🐞 Fix, ⚛️ FE
